# Generated by Django 4.0.4 on 2022-09-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coderequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('hash', models.CharField(max_length=200)),
                ('hash_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('close_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'E-Pin Requests',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tokens', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('levels', models.IntegerField(null=True)),
                ('ref_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Member Earnings',
            },
        ),
        migrations.CreateModel(
            name='Epin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epin', models.IntegerField(unique=True)),
                ('amount', models.IntegerField(null=True)),
                ('issue_to', models.IntegerField(null=True)),
                ('generate_time', models.DateField(null=True)),
                ('generated_by', models.CharField(default='Admin', max_length=100)),
                ('used_by', models.IntegerField(null=True)),
                ('used_time', models.DateField(null=True)),
                ('status', models.CharField(default='un used', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'E-Pins',
            },
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('address_proof', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
            options={
                'verbose_name_plural': 'Member KYC',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('sponsor', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('join_date', models.DateField(null=True)),
                ('staking', models.IntegerField(null=True)),
                ('topup', models.IntegerField(null=True)),
                ('tokens', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('topupdate', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'All Member',
            },
        ),
        migrations.CreateModel(
            name='Member_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('taxnumber', models.CharField(max_length=50, null=True)),
                ('walletaddress', models.CharField(max_length=50, null=True)),
                ('nominee', models.CharField(max_length=40, null=True)),
                ('nominee_relation', models.CharField(max_length=30, null=True)),
                ('dob', models.CharField(max_length=40, null=True)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('add_proof', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
            options={
                'verbose_name_plural': 'Member Profile',
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('reward_name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('paid_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Member Rewards',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Member Wallet',
            },
        ),
        migrations.CreateModel(
            name='Widhdraw_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('paid_date', models.DateField(null=True)),
                ('trans_detail', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Make Payment',
            },
        ),
    ]
