# Generated by Django 4.0.4 on 2022-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_closingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='staking',
        ),
        migrations.AddField(
            model_name='member',
            name='dividend',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
